// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQI1xfKBXQvssUuian8DzGaMrOCeIWBuQ',
    appId: '1:391015804587:web:95ca613145299054b451ee',
    messagingSenderId: '391015804587',
    projectId: 'iron-project-new',
    authDomain: 'iron-project-new.firebaseapp.com',
    databaseURL: 'https://iron-project-new-default-rtdb.firebaseio.com',
    storageBucket: 'iron-project-new.firebasestorage.app',
    measurementId: 'G-8XL1308RQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0nsW29V_Uk_i9BYk8KnCR5eGWreaa66c',
    appId: '1:391015804587:android:8b890b49d3b030cab451ee',
    messagingSenderId: '391015804587',
    projectId: 'iron-project-new',
    databaseURL: 'https://iron-project-new-default-rtdb.firebaseio.com',
    storageBucket: 'iron-project-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9bLe_ejqoJRKuWp3ViKliwH0sqirFJao',
    appId: '1:391015804587:ios:d70ae2438b53d7a4b451ee',
    messagingSenderId: '391015804587',
    projectId: 'iron-project-new',
    databaseURL: 'https://iron-project-new-default-rtdb.firebaseio.com',
    storageBucket: 'iron-project-new.firebasestorage.app',
    iosBundleId: 'com.example.ironProjectNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9bLe_ejqoJRKuWp3ViKliwH0sqirFJao',
    appId: '1:391015804587:ios:d70ae2438b53d7a4b451ee',
    messagingSenderId: '391015804587',
    projectId: 'iron-project-new',
    databaseURL: 'https://iron-project-new-default-rtdb.firebaseio.com',
    storageBucket: 'iron-project-new.firebasestorage.app',
    iosBundleId: 'com.example.ironProjectNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQI1xfKBXQvssUuian8DzGaMrOCeIWBuQ',
    appId: '1:391015804587:web:ea178902ecd0666fb451ee',
    messagingSenderId: '391015804587',
    projectId: 'iron-project-new',
    authDomain: 'iron-project-new.firebaseapp.com',
    databaseURL: 'https://iron-project-new-default-rtdb.firebaseio.com',
    storageBucket: 'iron-project-new.firebasestorage.app',
    measurementId: 'G-7LTZKXGV2M',
  );

}